/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#993100",
        "surface": "#fcf9f8",
        "on-primary-container": "#efefff",
        "on-background": "#1c1b1b",
        "surface-dim": "#dcd9d9",
        "primary": "#0040df",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#c8c6c3",
        "outline": "#747688",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f3f0ef",
        "tertiary-fixed": "#ffdbcf",
        "secondary-container": "#e4e2df",
        "tertiary-fixed-dim": "#ffb59b",
        "on-primary-fixed-variant": "#0035bd",
        "surface-container": "#f0eded",
        "background": "#fcf9f8",
        "primary-fixed-dim": "#b8c3ff",
        "on-secondary-fixed": "#1b1c1a",
        "secondary-fixed": "#e4e2df",
        "on-primary-fixed": "#001355",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#380d00",
        "on-surface-variant": "#434656",
        "on-secondary-fixed-variant": "#474745",
        "surface-bright": "#fcf9f8",
        "tertiary-container": "#c24100",
        "on-tertiary-fixed-variant": "#812900",
        "error": "#ba1a1a",
        "outline-variant": "#c4c5d9",
        "on-tertiary-container": "#ffece6",
        "secondary": "#5f5e5c",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "surface-container-high": "#eae7e7",
        "on-secondary": "#ffffff",
        "surface-tint": "#104af0",
        "on-secondary-container": "#656462",
        "surface-variant": "#e5e2e1",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "inverse-primary": "#b8c3ff",
        "surface-container-low": "#f6f3f2",
        "primary-container": "#2d5bff",
        "inverse-surface": "#313030",
        "primary-fixed": "#dde1ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
        body: ["Geist", "sans-serif"]
      }
    },
  },
  plugins: [],
}
